name: FullStackCICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Build Frontend
      run: |
        cd frontend
        npm run build

    - name: Archive Frontend Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: frontend-build
        path: frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Frontend Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: frontend-build

    - name: Set up Node.js for Backend
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Backend Dependencies
      run: npm install

    - name: Start Backend Server (adjust as needed)
      run: npm start &

    - name: Wait for Backend to Start
      run: sleep 10s  # Adjust if needed

    - name: Run Backend Integration Tests (if applicable)
      run: npm test

    - name: Deploy Backend (adjust deployment script)
      run: |
        # Example: Deploy to a hosting service like Heroku
        npx heroku login
        npx heroku git:remote -a your-heroku-app-name
        git push heroku main
